### ISSUE TITLE
Empty elements throw exception

### ISSUE THREAD

**Issue by tomi44g** [Wisetax/xml2object#2]
Extracting value of an empty element (e.g. declared using self closing tag) throws an exception in strict mode. 
Since the element is present it should rather extract an empty string.

``` js
test('Self closing elements should be supported', (t) => {

    const xml = "\
  <HEAD> \
    <TITLE>My title</TITLE> \
    <VERSION/> \
  </HEAD>"

    const extractor = xml2Obj.extract(xml, {
        title: '/HEAD/TITLE/text()',
        version: '/HEAD/VERSION',
    })

    t.is(extractor.title, 'My title')
    t.is(extractor.version, '')
})
```

**Comment by stanBienaives** [comment]
Hello @tomi44g.  Thanks for this. 

I think it make sens that that version should return `undefined` since your are requesting for the full node and not a specific attribute. 

If you wishes to grab the Text node inside you should use the path: 
`/HEAD/VERSION/text()``

However in the case of a self closing tag the no Text Node is present. 

Therefore I suggest to do the following: 

```javascript 
const extractor = xml2Obj.extract(xml, {
    title: '/HEAD/TITLE/text()',
   version: {
       path: '/HEAD/VERSION/text()', // Grab the text node value
       default: '', // Returns empty string if the text node is missing
       tolerance: true, // Prevent to fail when text  node is missing
   }
})
```

*IMPORTANT NOTE* You need to upgrade to version `1.4.4` where I fixed #3 a bug about empty string not supported as default values
